INSERT INTO LIBRARY_USER(ID, USER_NAME) VALUES (2, 'Joao');
INSERT INTO LIBRARY_USER(ID, USER_NAME) VALUES (3, 'Pedro');
INSERT INTO LIBRARY_USER(ID, USER_NAME) VALUES (4, 'Marta');
INSERT INTO BOOK(ID, TITLE, GENDER, DESCRIPTION, YEAR_OF_PUBLICATION, AUTHOR) VALUES (2, 'A arte da guerra', 'Historic', 'A description', 1500, 'Sun Tzu');
