INSERT INTO LIBRARY_USER(ID, USER_NAME, USER_ROLE) VALUES (2, 'Joao', 'EMPLOYEE');
INSERT INTO LIBRARY_USER(ID, USER_NAME, USER_ROLE) VALUES (3, 'Pedro', 'EMPLOYEE');
INSERT INTO LIBRARY_USER(ID, USER_NAME, USER_ROLE) VALUES (4, 'Marta', 'CUSTOMER');
INSERT INTO BOOK(ID, TITLE, GENDER, DESCRIPTION, YEAR_OF_PUBLICATION, AUTHOR) VALUES (2, 'A arte da guerra', 'Historic', 'A description', 1500, 'Sun Tzu');
